### ISSUE TITLE
writing text using a bitmap font

### ISSUE THREAD

**Issue by nerdess** [sallar/matrix-display-store#6]
can you provide an example on how to use store.write(x, y, text, font, size, color)? 

afaik some kind of bitmap font is needed but i am not sure how to embed this kind of font correctly...

**Comment by sallar** [comment]
@nerdess you can import any of the fonts available in this directory: https://github.com/sallar/matrix-display-store/tree/master/src/led/fonts and use them. Example:

```ts
import { Color, IMatrix, Store, TomThumb } from "matrix-display-store";
// ...
// ...
store.write(15, 8, "test", TomThumb, 1, Color.rgba(0, 255, 0));
```

Let me know if it's still unclear. Thanks!

**Comment by sallar** [comment]
@nerdess I have also written a short description of how they work here: https://github.com/sallar/led-matrix-simulator#bitmap-fonts

**Comment by nerdess** [comment]
ahhh nice, this helped me a lot...thx :)
